package personalproject.social.network.model;

public enum EReportType {
	INAPPROPRIATE_CONTENT, INAPPROPRIATE_IMAGES, IMPERSONATION_OR_MIMICRY, ABUSE_OR_HARASSMENT, COPYRIGHT_VIOLATION,
	SPAM_OR_FRAUD, OTHER_REASON
}
